---
magento_language: "en_US"
magento_currency: "INR"
magento_admin_frontname: "admin"
magento_admin_user: admin
magento_admin_password: "Salm0n1111"
magento_admin_email: "khushboo.shukla@wundermanthompson.com"
magento_admin_firstname: ""
magento_admin_lastname: "Shukla"
magento_crypt_key: a7e7ab5cd150d7d7044eeada37af527b
magento_base_url: "http://172.28.128.7"
magento_root_dir: "/vagrant/magento2"
