---

- name: delete default.conf
  become: yes
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Reload nginx

- name: Copy default.conf
  become: yes
  copy: 
    src: default.conf 
    dest: /etc/nginx/conf.d/default.conf
    mode: 0755
  notify: Reload nginx
